### ISSUE TITLE
Negatif Zaman

### ISSUE THREAD

**Issue by AliKarahisar** [umurakbulut/timer.js#1]
Negatif zamanlarda da sayma yapar, bu işlemin kontrol edilmesi lazım.
![screen shot 2018-08-08 at 22 17 23](https://user-images.githubusercontent.com/26181296/43859354-0a16b172-9b59-11e8-9d37-c8e47db6dd7f.jpg)

**Comment by umurakbulut** [comment]
Kullanıcı eğer negatif sayı girmeye çalışırsa, pozitif yapılıp sayaç öyle başlatılıyor. @AliKarahisar
